version: "3.9"

services:
  mariadb:
    image: mariadb:11.7.2
    container_name: mariadb

    restart: always

    ports:
      - "3308:3306"

    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: moltaai
      MARIADB_USER: nirmala
      MARIADB_PASSWORD: nirmala@123

    volumes:
      - mariadb_data:/var/lib/mysql

    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data: